### ISSUE TITLE
Questions about the ecosystem

### ISSUE THREAD

**Issue by Jakemate977** [ADKSoftware/xoc#1]
Why should we use this language over something like rust or golang?
What is the point of compiling it to C++ and not to binaries?
How do you expect to this language grow without a package manager or sdks support?

**Comment by ClaraCastells** [comment]
Hi,
Xoc is in process of rewriting right now.
Soon we will introduce amazing features for people that want to develop inside Xoc and release libraries.

Thanks for your comment, we will seriously think your purpose.

**Comment by Jakemate977** [comment]
It will be nice and faster if instead of compiling it to C++ (or js, it doesn't explain very well to what does it compiles) compiles all to binaries like rust

**Comment by ClaraCastells** [comment]
Hi,
When finished, we will publish the  new source code bases in this repository, so you can open a pull request and propose your own changes. We will be glad to receive your PR.

Thanks for your comment, I'll keep this issue open if you want to make additional comment.
